spring.application.name=centroplus-connect

spring.datasource.url=jdbc:sqlite:../database/centroplus.db
spring.datasource.driver-class-name=org.sqlite.JDBC

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect